export const books = [
    {
        id: 1,
        title: "Atomic Habits by James Clear",
        url: "https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg",
        originalPrice: 27.99,
        salePrice: 15.99,
        rating: 5,
        stripeID: "price_1OxDDtDH16DQa3RUr6Cx0O4z",
        category: "Self-Help",
        summary1: "This best-selling book by James Clear provides practical strategies for forming good habits, breaking bad ones, and mastering the tiny behaviors that lead to remarkable results.",
        summary2: "Originally priced at $27.99, it's now available for $15.99, making it an affordable investment in self-improvement."
    },
    {
        id: 2,
        title: "The Alchemist by Paulo Coelho",
        url: "https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL.jpg",
        stripeID: "price_1OxESZDH16DQa3RUP6ie2WSI",
        originalPrice: 16.99,
        salePrice: null,
        rating: 5,
        category: "Fiction",
        summary1: "Paulo Coelho's timeless novel tells the story of a young shepherd on a journey to discover the meaning of life, blending mysticism, wisdom, and self-discovery.",
        summary2: "While the sale price is not specified, its original price of $16.99 reflects its enduring popularity and the profound impact it has on readers."
    },
    {
        id: 3,
        title: "Where the Crawdads Sing by Delia Owens",
        url: "https://m.media-amazon.com/images/I/81HA6TJ5K-L._AC_UF1000,1000_QL80_.jpg",
        originalPrice: 26.99,
        salePrice: 19.99,
        stripeID: "price_1OxEbWDH16DQa3RUcPvvw00A",
        rating: 4.5,
        category: "Mystery",
        summary1: "This novel by Delia Owens combines a gripping murder mystery with a coming-of-age story set in the marshlands of North Carolina.",
        summary2: "Initially priced at $26.99, it is now available for $19.99, making it a great choice for fans of literary fiction and suspense."
    },
    {
        id: 4,
        title: "Becoming by Michelle Obama",
        url: "https://images-na.ssl-images-amazon.com/images/I/81h2gWPTYJL.jpg",
        originalPrice: 32.50,
        salePrice: 20.55,
        stripeID: "price_1OxEeBDH16DQa3RUsnad8xr9",
        rating: 5,
        category: "Memoir",
        summary1: "In her deeply personal memoir, former First Lady Michelle Obama shares the experiences that have shaped her, from her childhood in Chicago to her years in the White House.",
        summary2: "Originally sold for $32.50, it is now available for $20.50, making it a valuable read for anyone interested in her inspiring story."
    },
    {
        id: 5,
        title: "The Silent Patient by Alex Michaelides",
        url: "https://m.media-amazon.com/images/I/91lslnZ-btL._AC_UF1000,1000_QL80_.jpg",
        originalPrice: 26.99,
        salePrice: 16.99,
        stripeID: "price_1OxEfdDH16DQa3RUgZ0bm87o",
        rating: 4.5,
        category: "Thriller",
        summary1: "This psychological thriller by Alex Michaelides tells the story of a woman who shoots her husband and then never speaks another word, unraveling a shocking twist.",
        summary2: "Originally priced at $26.99, the book’s sale price of $16.99 offers readers a thrilling experience at a discount."
    },
    {
        id: 6,
        title: "Educated by Tara Westover",
        url: "https://images-na.ssl-images-amazon.com/images/I/81WojUxbbFL.jpg",
        originalPrice: 28.00,
        salePrice: 18.45,
        rating: 4.5,
        stripeID: "price_1OxEgwDH16DQa3RUtURFmUra",
        category: "Memoir",
        summary1: "Tara Westover’s memoir chronicles her journey from a survivalist family in rural Idaho to earning a PhD from Cambridge University, despite never attending school until the age of seventeen.",
        summary2: "With a significant price reduction from $28.00 to $18.00, this book offers a compelling and inspiring read about resilience and the power of education."
    },
    {
        id: 7,
        title: "The Midnight Library by Matt Haig",
        url: "https://m.media-amazon.com/images/I/71aiTCR69YS._AC_UF1000,1000_QL80_.jpg",
        originalPrice: 26.00,
        stripeID: "price_1OxEiEDH16DQa3RUJF91gV7W",
        salePrice: 13.99,
        rating: 4,
        category: "Fantasy",
        summary1: "Matt Haig's novel explores the choices that go into a life well-lived through a library that allows people to see how their lives might have turned out differently.",
        summary2: "Originally priced at $26.00, the book’s current price of $13.99 makes it an accessible and thought-provoking read."
    },
    {
        id: 8,
        title: "The Catcher in the Rye by J.D. Salinger",
        url: "https://m.media-amazon.com/images/I/91fQEUwFMyL._AC_UF1000,1000_QL80_.jpg",
        originalPrice: 20.00,
        salePrice: 12.99,
        stripeID: "price_1OxEjMDH16DQa3RU2DUJnCoV",
        rating: 4.5,
        category: "Classic Literature",
        summary1: "J.D. Salinger's classic novel follows the story of Holden Caulfield, a teenager navigating the complexities of adolescence and society's expectations.",
        summary2: "Originally priced at $20.00, the book’s sale price of $12.99 offers readers a chance to own one of the most iconic novels of the 20th century."
    },
    {
        id: 9,
        title: "The Vanishing Half by Brit Bennett",
        url: "https://m.media-amazon.com/images/I/81ICvbFe2+L._AC_UF1000,1000_QL80_.jpg",
        originalPrice: 27.50,
        salePrice: null,
        stripeID: "price_1OxEljDH16DQa3RUIDckCMzw",
        rating: 4.5,
        category: "Fiction",
        summary1: "Brit Bennett’s novel explores the lives of twin sisters who grow up in a small, southern black community and choose very different paths in life.",
        summary2: "Though the sale price is not listed, the book's high rating and original price of $27.00 underscore its status as a bestseller."
    },
    {
        id: 10,
        title: "The Four Winds by Kristin Hannah",
        url: "https://m.media-amazon.com/images/I/91+CnxqOEQS._AC_UF1000,1000_QL80_.jpg",
        originalPrice: 28.99,
        salePrice: null,
        rating: 4,
        stripeID: "price_1OxEmtDH16DQa3RUigZ7XzeX",
        category: "Historical Fiction",
        summary1: "Set during the Great Depression, Kristin Hannah's novel tells a story of love, family, and resilience in the face of hardship.",
        summary2: "Despite its original price of $28.99, the lack of a listed sale price suggests the book’s enduring popularity and critical acclaim."
    },
    {
        id: 11,
        title: "A Promised Land by Barack Obama",
        url: "https://m.media-amazon.com/images/I/91-6R0VxRiL._AC_UF1000,1000_QL80_.jpg",
        originalPrice: 45.99,
        salePrice: null,
        stripeID: "price_1OxEo2DH16DQa3RU8wVpZcwY",
        rating: 5,
        category: "Memoir",
        summary1: "In this highly anticipated memoir, former President Barack Obama reflects on his early political career, his presidency, and the moments that defined his leadership.",
        summary2: "With no sale price listed and an original price of $45.00, it’s clear this book is a valuable piece of modern history and leadership."
    },
    {
        id: 12,
        title: "The Book Thief by Markus Zusak",
        url: "https://m.media-amazon.com/images/I/914cHl9v7oL._AC_UF1000,1000_QL80_.jpg",
        originalPrice: 14.99,
        salePrice: 9.99,
        rating: 4.5,
        stripeID: "price_1OxEoxDH16DQa3RUOmV2ImoL",
        category: "Historical Fiction",
        summary1: "Set in Nazi Germany, Markus Zusak's novel tells the powerful story of a young girl who finds solace in stealing books and sharing them with others, narrated by Death itself.",
        summary2: "Initially valued at $14.99, the book is currently priced at $9.99, making it a moving and accessible read for all ages."
    },
];
